name: Increment version

permissions:
  contents: write

on:
  workflow_call:

jobs:
  increment-version:
    name: Increment Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Get version config
        run: |
          curl https://github.com/Health-Education-England/tis-poc-automated-versioned-releases-reusable/blob/main/.github/workflows/auto-version-config/.versionrc > .versionrc
          curl https://github.com/Health-Education-England/tis-poc-automated-versioned-releases-reusable/blob/main/.github/workflows/auto-version-config/terraform-version-updater.js > terraform-version-updater.js

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.0

      - name: Increment version
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          npx @dwmkerr/standard-version
          git push --follow-tags
