name: PR Analysis - Common

permissions:
  pull-request: read

on:
  workflow_call:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Lint commits
        uses: wagoid/commitlint-github-action@v5.4.4
